### ISSUE TITLE
Sticker Logistics

### ISSUE THREAD

**Issue by geospatialem** [maptimemsp/organizers#10]
A few things that popped into my head are:
1. What is the sticker website we ordered from?
2. What sticker type did we elect?
3. How many stickers did we order?
4. Is there a final .png (or similar) file that was used for the print?
5. Any other items I am likely forgetting.

**Comment by fawcett** [comment]
That looks like a pretty good list.  It would be great to get the original files saved on Github.  That way it would be easy to print more.

While the original sticker design is really cool, it might be fun to come up with new designs for future runs.

**Comment by mtaylorlong** [comment]
I have the original files for the logo, the stickers and the buttons – I'll drop them into a folder on this repo. Also, I totally agree that making new stickers for each order would be fun. Keeps things fresh.

**Comment by fawcett** [comment]
The collectable MaptimeMSP sticker series...

**Comment by geospatialem** [comment]
:heart: it!! :+1:

**Comment by mtaylorlong** [comment]
Added a page to the wiki called [Graphics](https://github.com/MaptimeMSP/organizers/wiki/Graphics). I believe that wraps up this issue.

**Comment by geospatialem** [comment]
:guitar: :star2: **!**
