### ISSUE TITLE
September 2015 Meeting

### ISSUE THREAD

**Issue by fawcett** [maptimemsp/organizers#12]
Do we have any ideas for topics, locations, or dates for the September meeting?  Let's start the conversation.

**Comment by geospatialem** [comment]
@fawcett, I've sent an e-mail to Kat asking if she would have interest in presenting on **_Typography/Cartography_** and hope @lpuhl can also give a presentation to the group as well.

@lpuhl was working on the location and date for September, and hopefully a few months beyond as well. I haven't heard anything yet, but I will check-in with her in case she doesn't see notifications here on the GitHubs.

I'll shoot back an update here regarding both Kat's response, and the location as soon as I learn more!

**Comment by geospatialem** [comment]
@fawcett I just heard back from Liz. She's working with a few locations to nail down September's location and she's on board for a presentation.

I haven't heard from Kat on a yay/nay for a presentation, but I suspect I'll hear something in the next week or so. 

**Is there anyone else you can think of that would be a good speaker? Or a good exercise we could work on together you've seen from other Maptime events?**
