### ISSUE TITLE
Organize upcoming meetup events (June - October 2016)

### ISSUE THREAD

**Issue by geospatialem** [maptimemsp/organizers#15]
Hey all,

I believe this month is the last one we have scheduled, maybe we can set up the next 3-4 meetings in the coming weeks? 

A few notes:
- I was able to connect with one of the [OpenTwinCities](http://www.meetup.com/opentwincities) organizers at Geo:Code 2.0 a few months back, and they had interest in doing a joint event this summer. Maybe we can latch onto one of their events, help with a topic idea, and provide 🍕  at one of their host sites? (Or any other ideas you all have) 😄 
- We've got this [amazing list](https://github.com/maptimemsp/organizers/wiki/Event-Topic-Ideas-%28Future%29) still, anything in particular you think everyone would be interested in? Or, anything any of you have interest in?
- Since we're starting to get into the good outdoors weather, maybe we can do an event outside, too?

**So, what say you all? Maybe we can do a Google Hangout next week (the first week of May)?**

Talk soon,
Kitty

**Comment by lpuhl** [comment]
Hi Kitty! Sorry for the radio silence. Maybe a Hangout next week? Tuesday, Wed, and Thursday are pretty open for me.

**Comment by geospatialem** [comment]
No worries at all, @lpuhl! And perfect, I'm free Tuesday, Wednesday, and Thursday evening as well! @fawcett: Any of those evenings work for you? We could start a session at 5 p.m. If that works for everyone? I'm guessing it would take 30-45 minutes.

**Comment by lpuhl** [comment]
Egad, I'm sorry for dropping off again. I was out of town for a couple days, and this week got really busy. 

I don't suppose you guys would be able to get to the Borchert library a little early on Tuesday for an organizers' huddle? Like around 4:45?

**Comment by geospatialem** [comment]
@lpuhl No worries! I won't be able to get there too early, but early enough to get the :pizza:s. I think a Hangout would still be best for me, and this weekend, and next week is shot for me. I think I've got something setup for June with Open Twin Cities, so if we met the following week (May 23-27) we can plan July through the early fall. How does that sound?

**Comment by fawcett** [comment]
I could meet for a bit after the Borchert meeting.  I could also do a hangout, but the week of the 23-27 is bad because I will be in LaCrosse for UMGEOCON.

**Comment by geospatialem** [comment]
I can meet after for a bit, but not too late. Let's plan on that. Also, if either of you can please put on a hold on Tues 6/28. I'll fill you in next week!

**Comment by lpuhl** [comment]
Sounds good!

**Comment by geospatialem** [comment]
@bitner, @fawcett, @lpuhl: Does the following capture our discussions from last week? 

☑️ = completed/confirmed

## Locations:
- June 28 (Tues): University of Minnesota - Mpls campus ☑️  
- July 21 (Thurs): St. Anthony Park Library, St. Paul ☑️  
- August 18 (Thurs): Washburn Library, Minneapolis ☑️  
- September: Highland Park Library, Minneapolis ☑️
- October 27 (Thurs): GIS/LIS Conference, Duluth ☑️  

## Topics:
- June: Collaborative work session w/ Open Twin Cities using CartoDB (feat. Molly McDonald) ☑️ 
- July: Handmade Maps & Map Art (feat. Jackie Kovarik) ☑️  
- August: Open Street Map + Open Data (feat. Joe Sapletal) ☑️  
- September: TBD
- October: [Editing the National Map](http://nationalmap.gov/TheNationalMapCorps) ☑️
