### ISSUE TITLE
List of Event Locations and Instructions

### ISSUE THREAD

**Issue by mtaylorlong** [maptimemsp/organizers#7]
Let's put this in the Wiki too

**Comment by mtaylorlong** [comment]
I started a wiki page for [Venues](https://github.com/MaptimeMSP/organizers/wiki/Venues) and added contact info for Tawnee at CoCo. I also added entries for Washburn and Highlands Park Libraries, but one of y'all gets to fill those out.

**Comment by fawcett** [comment]
Thanks for documenting all of this Taylor!

**Comment by geospatialem** [comment]
Thanks for putting the list together, @mtaylorlong! :+1: It looks like we've got some great information inputted into the wiki. 

Anything else jump out that you can fill in based on your experiences? If not, we could close the issue for now and build upon it moving forward.

**Comment by mtaylorlong** [comment]
CoCo was the only space where there was a routine in place. There's no other essential info to share about the libraries. You just go to the websites and follow the instructions.
